/**
  DO NOT EDIT
  This file is auto-generated by uefi-aware compiler toolchain
  Contact steven.shi@intel.com for more details
**/

#include "AutoGen.h"
#include <Base.h>
#include <Library/SafeIntLib.h>
#include <Library/BaseLib.h>
#include  <Library/DebugLib.h>
